### ISSUE TITLE
Some work needed in accounts App

### ISSUE THREAD

**Issue by PhysicistSouravDas** [Python-Abia/Get-a-Doc#47]
Following things needed to be fixed:
* In the accounts app of this project, `ImageField` is user, for which to work, `Pillow` is required. 
* The magic `__str__` method also needs to be fixed in *models.py*. 
* The model `UserProfile` is not subclassing any Django model, that's why creating a UserProfile instance is throwing error.
* One more good feature will be to add `UserProfile` model in admin with some features like filtering, searching, etc.
* `phone` field in `UserProfile` should be validated so that no one can enter any random unusual characters.

**Comment by psalmskalu** [comment]
Okay. that's great. get on with it!

**Comment by PhysicistSouravDas** [comment]
@psalmskalu This issue was resolved with the Pull Request #48 which is successfully merged with the `master` branch.
